### ISSUE TITLE
Extension creates two vertical lines, and reloading/reopening editor does not fix it.

### ISSUE THREAD

**Issue by DolphyWind** [franneck94/Vscode-C-Cpp-Config#4]
As mentioned in title, when I run C/C++ Config: Generate C++ config files option, It creates two vertical lines in my editor that I am unable to get rid of. Here's a screenshot of my editor
![image](https://user-images.githubusercontent.com/47641431/230145676-9743204f-01e7-4ecf-8bc8-55f424106b57.png)

**Comment by franneck94** [comment]
![image](https://user-images.githubusercontent.com/20141069/230425577-dab94b6f-507f-45dc-92fe-7c2c8002d1cc.png)
