### ISSUE TITLE
Fehlermeldung result is an error

### ISSUE THREAD

**Issue by SirHesti** [franneck94/Vscode-C-Cpp-Config#5]
Hallo Franneck
Nur die C/C++ Config installiert leider mit Fehlermeldung sobald malk View->generate startet. Sihe Bildschirmfoto. Auch den Runner & Extensionspack  hab ich danach installiert auch dann gleiches Ergebnis.
Hab ich was übersehen ?
MfG Hesti
![Screenshot 2023-04-24 113111](https://user-images.githubusercontent.com/51073539/233963676-f2d49c6d-f0d7-4549-945d-19bde2af6ec9.png)

**Comment by SirHesti** [comment]
![Screenshot 2023-04-28 061806](https://user-images.githubusercontent.com/51073539/235053379-4cf1dd91-2962-4fa0-933e-703d286986a2.png)
Gladly, here is a screenshot again. 
MfG Hesti

**Comment by franneck94** [comment]
It seems like you havnt opened a folder in vscode
